/** Opt-in explicit lifecycle contracts for the declaration-only DSL prototype. */

export { defineRecipe } from "./core/agent.ts";
export { withRecovery } from "./core/operations.ts";
export { defineWorkflow } from "./core/workflow.ts";

export type { Ctx, ReviewCtx, WorkflowCtx, WorkspaceCtx } from "./core/workflow.ts";

export type {
  CancellationOnlyRecoverableOperationConfig,
  ConditionalCleanupOperationDefinition,
  CompensatedRecoverableOperationConfig,
  DirectOperationDefinition,
  AdvancedOperationAuthorizeOptions,
  AdvancedOperationInvocationOptions,
  OperationApi,
  OperationAttemptAmbiguous,
  OperationAttemptCancellationIdempotencyOf,
  OperationAttemptCancellationInputOf,
  OperationAttemptCancellationOf,
  OperationAttemptCandidateOf,
  OperationAttemptCompensationInputOf,
  OperationAttemptCompensationOf,
  OperationAttemptIdempotencyOf,
  OperationAttemptIntent,
  OperationAttemptNotCommitted,
  OperationAttemptPrimaryOf,
  OperationAttemptRecoveryOf,
  OperationAttemptRef,
  OperationAttemptRefMarker,
  OperationAttemptResult,
  OperationAttemptSucceeded,
  OperationAuthorizationCandidateOf,
  OperationAuthorizationDefinitionOf,
  OperationAuthorizationOf,
  OperationAuthorizationPolicy,
  OperationAuthorizationRef,
  OperationAuthorizeOptions,
  OperationCancellationEvidenceBase,
  OperationCancellationInputMapper,
  OperationCancellationRecoveryPlan,
  OperationCancellationRegistration,
  OperationCancellationResult,
  OperationCancellationSucceeded,
  OperationCancellationUnsuccessful,
  OperationCandidateDefinitionOf,
  OperationCandidateInputOf,
  OperationCandidateRef,
  OperationCompensatedRecoveryPlan,
  OperationCompensationInputMapper,
  OperationCompensationRegistration,
  OperationExecutionReceipt,
  OperationFailureDetail,
  OperationFn,
  OperationInputOf,
  OperationInvocationOptions,
  OperationOutputOf,
  OperationPrepareOptions,
  OperationRecoveryCandidateIdentity,
  OperationRecoveryCandidateRef,
  OperationRecoveryEvidenceBase,
  OperationRecoveryResult,
  OperationRecoveryState,
  OperationRecoveryStateMarker,
  OperationRecoverySucceeded,
  OperationRecoveryUnsuccessful,
  OperationReceiptAttemptOf,
  OperationReceiptCompensationInputOf,
  OperationReceiptCompensationOf,
  OperationRunAuthorizationOptions,
  OperationUnsuccessfulDisposition,
  ProtectedOperationAuthorizationPolicy,
  ProtectedOperationDefinition,
  ProtectedOperationExecution,
  ProtectedOperationRunOptions,
  RecoverableOperationInvocationOptions,
  RecoverableCancellationConfig,
  RecoverableCompensationConfig,
  RecoverableOperationAttemptOf,
  RecoverableOperationDefinition,
  RecoverableOperationReceipt,
  RecoverableOperationReceiptIdentity,
  RecoverableOperationReceiptMarker,
  RecoverableOperationRunOptions,
  RecoverableOperationRunResult,
  RecoverableOperationStateOf,
  RecoverableOperationTypes,
  RecoverableOperationTypesOf,
  RecoverableOperationPrimaryOf,
  RegisteredOperationCancellation,
  RegisteredOperationRecovery,
  RegisteredOperationRecoveryPlan,
} from "./core/operations.ts";

export type {
  AdvancedDeliveryAuthorizeOptions,
  AdvancedDeliveryInvocationOptions,
  DeliveryApi,
  DeliveryAuthorizationCandidateOf,
  DeliveryAuthorizationDefinitionOf,
  DeliveryAuthorizationRef,
  DeliveryAuthorizeOptions,
  DeliveryFn,
  DeliveryInvocationOptions,
  DeliveryOneShotRequest,
  DeliveryPrepareOptions,
  DeliveryReceipt,
  DeliveryRunAuthorizationOptions,
  DeliveryRunRequest,
  PromotionCandidateDefinitionOf,
  PromotionCandidateInput,
  PromotionCandidateRef,
  PromotionCandidateSnapshotOf,
  PromotionEvidence,
  PromotionProofs,
} from "./core/deliveries.ts";

export type {
  CheckInvocationOptions,
  CheckWaiverAttestationValue,
  CheckWaiverAuthorizeFn,
  CheckWaiverAuthorizeOptions,
  CheckWaiverAuthorizer,
  CheckWaiverPolicy,
  CheckWaiverRef,
  EligibleCheckWaiverPolicy,
  ExecutedCheckInvocationOptions,
  FailedCheckResultOf,
  CandidateExecutedCheckInvocationOptions,
  CandidateTrustedCheckInvocationOptions,
  TrustedCheckInvocationOptions,
  UnboundCheckInvocationOptions,
  WaivedCheckInvocationOptions,
  WaiverEligibleCheckDefinition,
} from "./core/checks.ts";

export type {
  EvidenceRef,
  PromotionProof,
  SubjectAttestation,
  WorkspaceSnapshotRef,
} from "./core/shared.ts";
