import { createElement, Fragment, type ReactNode } from "react";

/** Complete, dependency-free Weft visual foundation. Safe inside sandboxed workflow UI bundles. */
export const weftStyles = `
:root{--color-bg:#f2ede3;--color-surface:#faf9f5;--color-text:#141413;--color-accent:#cc785c;--color-accent-2:#5db8a6;--color-divider:#e2dbd1;--color-neutral-100:#f5f0e8;--color-neutral-200:#efe9de;--color-neutral-300:#e6dfd8;--color-neutral-400:#c4bdb2;--color-neutral-500:#8e8b82;--color-neutral-600:#6c6a64;--color-neutral-700:#55534d;--color-neutral-800:#3d3d3a;--color-neutral-900:#181715;--color-accent-100:#fbf1ec;--color-accent-200:#f6e2d8;--color-accent-300:#eac6b4;--color-accent-400:#dd9b80;--color-accent-500:#cc785c;--color-accent-600:#b8664c;--color-accent-700:#a9583e;--color-accent-800:#8a4630;--color-accent-900:#5e2f20;--color-accent-2-100:#eaf6f3;--color-accent-2-200:#d7ece7;--color-accent-2-300:#a9dbd0;--color-accent-2-400:#7fc9b9;--color-accent-2-500:#5db8a6;--color-accent-2-600:#489a8a;--color-accent-2-700:#35786b;--color-accent-2-800:#275a51;--color-accent-2-900:#1a3c36;--color-danger:#b0483a;--color-danger-bg:#f7e4e1;--color-term-bg:#181715;--color-term-text:#efe9de;--color-term-dim:#a09d96;--color-term-gutter:#5c584f;--color-field-bg:#fffefb;--shadow-sm:0 1px 3px rgba(20,20,19,.08);--shadow-md:0 4px 14px rgba(20,20,19,.1);--shadow-lg:0 18px 44px rgba(20,20,19,.18);--font-body:"Inter",-apple-system,system-ui,sans-serif;--font-heading:"Source Serif 4",Georgia,serif;--font-mono:"JetBrains Mono",ui-monospace,monospace;--radius-sm:8px;--radius-md:12px;--radius-pill:999px}
*,*::before,*::after{box-sizing:border-box}html,body,#root{height:100%}body{margin:0;background:var(--color-bg);color:var(--color-text);font-family:var(--font-body);font-size:15px;line-height:1.55;font-weight:400}#root{font-size:13px}h1,h2,h3,h4,h5,h6{margin:0;font-family:var(--font-heading);font-weight:400;line-height:1.12;letter-spacing:-.02em}p{margin:0}input,button,label,select,textarea{font-family:inherit}a{color:var(--color-accent-700);text-underline-offset:3px}a:hover{color:var(--color-accent)}::selection{background:rgba(204,120,92,.22)}:focus{outline:none}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible{outline:2px solid var(--color-accent);outline-offset:2px}button:focus:not(:focus-visible){outline:none}@keyframes weft-pulse{0%,100%{opacity:1}50%{opacity:.3}}
.weft-button{display:inline-flex;align-items:center;justify-content:center;gap:6px;cursor:pointer;text-decoration:none;font:inherit;font-size:12px;font-weight:500;line-height:1.2;color:var(--color-text);background:transparent;border:1px solid transparent;border-radius:var(--radius-sm);min-height:0;white-space:nowrap}.weft-button:disabled{opacity:.45;cursor:not-allowed}.weft-button--primary{background:var(--color-accent);color:var(--color-bg)}.weft-button--primary:hover{background:var(--color-accent-600)}.weft-button--primary:active{background:var(--color-accent-700)}.weft-button--secondary{border-color:var(--color-divider)}.weft-button--secondary:hover{background:color-mix(in srgb,var(--color-text) 7%,transparent)}.weft-button--secondary:active{background:color-mix(in srgb,var(--color-text) 14%,transparent)}.weft-button--outline{border-color:var(--color-accent);color:var(--color-accent-700)}.weft-button--outline:hover{background:var(--color-accent-100)}.weft-button--outline:active{background:var(--color-accent-200)}.weft-button--ghost{color:var(--color-accent)}.weft-button--ghost:hover{background:color-mix(in srgb,var(--color-accent) 10%,transparent)}.weft-button--ghost:active{background:color-mix(in srgb,var(--color-accent) 18%,transparent)}.weft-button--xSmall{padding:4px 9px}.weft-button--xSmallWide{padding:4px 11px}.weft-button--small{padding:5px 11px}.weft-button--smallWide{padding:5px 13px}.weft-button--medium{padding:6px 12px}.weft-button--mediumWide{padding:6px 14px}.weft-button--large{padding:6px 16px}.weft-button--round{border-radius:var(--radius-pill)}
.weft-toolbar{display:flex;align-items:center;gap:12px;min-height:48px;width:100%}
.weft-count-badge{font-family:var(--font-mono);font-size:10px;border-radius:var(--radius-pill);padding:1px 6px}.weft-fact{display:flex;flex-direction:column;gap:2px;padding:0 13px;border-left:1px solid var(--color-neutral-200)}.weft-fact__key{font-size:10px;letter-spacing:.09em;text-transform:uppercase;color:var(--color-neutral-500)}.weft-fact__value{font-family:var(--font-mono);font-size:12px;white-space:nowrap}.weft-fact--step{min-height:54px;justify-content:center;gap:4px;padding:9px 14px}.weft-fact--step .weft-fact__key{font-size:9px;font-weight:600}.weft-fact--step .weft-fact__value{color:var(--color-neutral-900);font-size:12px;font-weight:500}.weft-fact--queue{width:172px;flex:none;padding:0 12px}.weft-fact--queue .weft-fact__value{font-size:11px}.weft-fact--artifact{min-width:120px;padding:0 14px}.weft-fact--artifact .weft-fact__value{font-size:11px}.weft-fact--first{border-left:0;padding-left:0}.weft-hairline{flex:1;height:1px;background:var(--color-divider)}
.weft-kicker{font-size:10px;letter-spacing:.12em;text-transform:uppercase;font-weight:600;color:var(--color-accent-700)}.weft-kicker--large{letter-spacing:.1em;font-size:11px}.weft-kicker--inline{letter-spacing:.09em;color:var(--color-neutral-500);font-weight:400;white-space:nowrap}.weft-live-cursor{font-family:var(--font-mono);font-size:12px;color:var(--color-accent-400);animation:weft-pulse 1.2s infinite}.weft-mono-badge{font-family:var(--font-mono);font-size:10px;border-radius:var(--radius-pill);padding:2px 9px;white-space:nowrap;flex:none}.weft-mono-badge--boxy{border-radius:var(--radius-sm);padding:2px 6px;letter-spacing:.06em;text-transform:uppercase}.weft-mono-badge--truncating{flex:none;padding:1px 6px}.weft-pill-button{appearance:none;cursor:pointer;font:inherit;font-family:var(--font-mono);font-size:11px;border-radius:var(--radius-pill);padding:4px 11px;white-space:nowrap;background:var(--color-field-bg);border:1px solid var(--color-neutral-300);color:var(--color-neutral-700)}.weft-pill-button--on{background:var(--color-accent-200);border-color:var(--color-accent);color:var(--color-accent-800)}
.weft-control{width:100%;padding:6px 14px;font:inherit;color:var(--color-text);caret-color:var(--color-accent);background:var(--color-field-bg);border:1px solid var(--color-neutral-300);border-radius:var(--radius-sm);min-height:32px;font-size:12px;font-family:var(--font-mono)}.weft-control:hover{border-color:color-mix(in srgb,var(--color-text) 45%,transparent)}.weft-control:focus{outline:none;border-color:var(--color-accent);box-shadow:0 0 0 3px rgba(204,120,92,.15)}.weft-control--settings{min-height:34px;font-size:13px}.weft-select{width:fit-content;min-width:210px}.weft-textarea{font-size:12px;resize:vertical;max-width:520px;font-family:var(--font-body)}.weft-range{accent-color:var(--color-accent);flex:1}.weft-screen-title{font-size:34px}.weft-toggle{appearance:none;border:0;background:none;padding:0;cursor:pointer;display:inline-flex;align-items:center;gap:9px;width:fit-content}.weft-toggle__track{width:30px;height:17px;border-radius:var(--radius-pill);flex:none;display:inline-flex;align-items:center;padding:0 2px}.weft-toggle__knob{width:13px;height:13px;border-radius:var(--radius-pill);background:var(--color-surface);display:block}.weft-toggle__label{font-family:var(--font-mono);font-size:11px;color:var(--color-neutral-700)}
`;

/** Applies Weft tokens, reset, and component styles without a CSS import. */
export function WeftTheme({ children }: { children: ReactNode }) {
  return createElement(
    Fragment,
    null,
    createElement("style", { "data-weft-design-system": "" }, weftStyles),
    children,
  );
}
